logging:
  level:
    root: info

server:
  port: 8080
  tomcat:
    max-connections: 10000
    accept-count: 1000
    threads:
      max: 3000       # 최대 쓰레드 개수
      min-spare: 1000 # 최소 쓰레드 개수


spring:
  boot:
    admin:
      client:
        url:
          - http://localhost:8080 # 서버 주소

  application:
    name: api

  r2dbc:
    url: r2dbc:mysql://localhost:3320/autostore
    username: root
    password: root

  jpa:
    show-sql: true # sql 쿼리문을 콘솔에 보여주기 위함.
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate # 서버를 띄울 때 클래스 엔티티와 디비의 속성이 일치하는 지 확인 (create, update 등 여러 속성이 있음 --> validate 추천!)

  datasource:
    url: jdbc:mysql://localhost:3320/autostore # mysql 서버 연동 ?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root # db 비밀번호