#spring:
#  jpa:
#    show-sql: true
#    properties:
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl_auto: validate
#  datasource:
#    url: jdbc:mysql://localhost:3306/products?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root1234!!

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://autostore.cle2yiiugd0z.ap-southeast-2.rds.amazonaws.com:3306/autostoreDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234!!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update